name: Build and push Docker image

on:
  push:
    branches: [main]  # 当 main 分支有推送时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }} # 缓存依赖
      - name: Install dependencies
        run: npm install 


      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Alibaba Cloud Container Registry
        uses: docker/login-action@v1
        with:
          registry: crpi-l4eaw54bzztpe9af.cn-hangzhou.personal.cr.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t crpi-l4eaw54bzztpe9af.cn-hangzhou.personal.cr.aliyuncs.com/caihuaoo/cms_web .

      - name: Push Docker image
        run: |
          docker push crpi-l4eaw54bzztpe9af.cn-hangzhou.personal.cr.aliyuncs.com/caihuaoo/cms_web
